In [1]:
import pandas as pd
import os

import subprocess

In [3]:
# wza_kendalltau_results_bio1.csv'
# wza_results_lfmm_bio1.csv

In [2]:
tair = pd.read_csv('../key_files/TAIR10_GFF3_genes_transposons_formatted4topr_w_blocks.csv')

In [3]:
import pickle
dict_blocks = '../key_files/blocks_snpsid_dict.pkl'

with open(dict_blocks, 'rb') as file:
    dict_blocks = pickle.load(file)

reverse_mapping = {item: key for key, values in dict_blocks.items() for item in values}

In [7]:
sign_blocks_union_first_last_gen = pd.read_csv('sign_blocks_union_first_last_gen.csv')

In [8]:
df = sign_blocks_union_first_last_gen.copy()

In [9]:
bed_file_name = "sign_blocks_union_first_last_gen.bed"

In [10]:
blocks_annotated_file = "sign_blocks_union_first_last_gen_blocks_annotated.txt"

In [11]:
gene_ids_file = 'sign_blocks_union_first_last_gen_gene_ids.txt'

In [12]:
gff_filtered_file = 'sign_blocks_union_first_last_gen.gff'

In [13]:
nucleotide_seq_sign_genes = 'sign_blocks_union_first_last_gen_nucleotide_seq.fa'

In [100]:
# Open the BED file for writing
with open(bed_file_name, "w") as bed_file:
    for block in df['block']:
        if block in dict_blocks:
            # Extract SNPs for the block
            snps = dict_blocks[block]
            
            # Assuming the format of SNP is like '1_291' where '1' is the chromosome and '291' is the position
            # We need to find the min and max positions for the block to create the start-end range
            chrom_positions = [snp.split('_') for snp in snps]
            chrom = chrom_positions[0][0]  # The chromosome, assuming all SNPs are from the same chromosome
            
            # Prepend 'Chr' to the chromosome name to match GFF naming convention
            chrom = f"Chr{chrom}"
            
            # Get the minimum and maximum position for the block
            start = min(int(pos) for chrom, pos in chrom_positions)
            end = max(int(pos) for chrom, pos in chrom_positions)
            
            # Write the block information in BED format: chrom, start, end, block name
            bed_file.write(f"{chrom}\t{start}\t{end}\t{block}\n")

print("BED file has been created with 'Chr' prefix in chromosome names.")

BED file has been created with 'Chr' prefix in chromosome names.

In [101]:
pd.read_csv('../key_files/TAIR10_GFF3_genes_transposons.gff', sep='\t', comment='#', header=None )

,0,1,2,3,4,5,6,7,8
0,Chr1,TAIR10,chromosome,1,30427671,.,.,.,ID=Chr1;Name=Chr1
1,Chr1,TAIR10,gene,3631,5899,.,+,.,ID=AT1G01010;Note=protein_coding_gene;Name=AT1...
2,Chr1,TAIR10,mRNA,3631,5899,.,+,.,ID=AT1G01010.1;Parent=AT1G01010;Name=AT1G01010...
3,Chr1,TAIR10,protein,3760,5630,.,+,.,ID=AT1G01010.1-Protein;Name=AT1G01010.1;Derive...
4,Chr1,TAIR10,exon,3631,3913,.,+,.,Parent=AT1G01010.1
...,...,...,...,...,...,...,...,...,...
656304,Chr5,TAIR10,transposon_fragment,26893818,26893895,.,-,.,Parent=AT5TE96885
656305,Chr5,TAIR10,transposable_element,26925227,26925333,.,+,.,ID=AT5TE97000;Name=AT5TE97000;Alias=ATHILA8B
656306,Chr5,TAIR10,transposon_fragment,26925227,26925333,.,+,.,Parent=AT5TE97000
656307,Chr5,TAIR10,transposable_element,26965908,26966653,.,-,.,ID=AT5TE97150;Name=AT5TE97150;Alias=ATREP9
656308,Chr5,TAIR10,transposon_fragment,26965908,26966653,.,-,.,Parent=AT5TE97150

In [103]:
bed_file_name

'sign_blocks_union_first_last_gen_BH.bed'

In [104]:
## this will, based on the TAIR10_GFF3_genes_transposons cehck the intersectionin between the bed file fo hte singificant blocks and the genes 
gff_file = "../key_files/TAIR10_GFF3_genes_transposons.gff"  # Replace with your actual GFF3 file path

# Construct the command to load the bedtools module and run the intersect command
cmd = f"""
module load BEDTools/2.29.2; \
bedtools intersect -wb -a {bed_file_name} -b {gff_file} > {blocks_annotated_file}
"""

# Run the command
try:
    subprocess.run(cmd, shell=True, check=True, executable="/bin/bash")  # Use bash to run the command
    print(f"Intersection complete. Results saved in {blocks_annotated_file}")
except subprocess.CalledProcessError as e:
    print(f"Error running bedtools: {e}")

Intersection complete. Results saved in sign_blocks_union_first_last_gen_blocks_annotated_BH.txt

In [14]:
annot = pd.read_csv(blocks_annotated_file, sep='\t', header=None)

In [15]:
annot.columns = [
    'block_chrom', 'block_start', 'block_end', 'block_id',  # From BED file
    'gene_chrom', 'source', 'feature', 'gene_start', 'gene_end',  # From GFF file
    'score', 'strand', 'frame', 'attribute'  # From GFF file
]

In [17]:
annot[annot['block_id'] == '4_801']

,block_chrom,block_start,block_end,block_id,gene_chrom,source,feature,gene_start,gene_end,score,strand,frame,attribute
480,Chr4,7255726,7256406,4_801,Chr4,TAIR10,gene,7254049,7256406,.,+,.,ID=AT4G12110;Note=protein_coding_gene;Name=AT4...
481,Chr4,7255726,7256406,4_801,Chr4,TAIR10,mRNA,7254049,7256406,.,+,.,ID=AT4G12110.1;Parent=AT4G12110;Name=AT4G12110...
482,Chr4,7255726,7256004,4_801,Chr4,TAIR10,protein,7254197,7256004,.,+,.,ID=AT4G12110.1-Protein;Name=AT4G12110.1;Derive...
483,Chr4,7255823,7255856,4_801,Chr4,TAIR10,exon,7255824,7255856,.,+,.,Parent=AT4G12110.1
484,Chr4,7255823,7255856,4_801,Chr4,TAIR10,CDS,7255824,7255856,.,+,0,"Parent=AT4G12110.1,AT4G12110.1-Protein;"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,Chr4,7256537,7261180,4_801,Chr4,TAIR10,mRNA,7256538,7261180,.,-,.,ID=AT4G12120.1;Parent=AT4G12120;Name=AT4G12120...
575,Chr4,7256686,7260914,4_801,Chr4,TAIR10,protein,7256687,7260914,.,-,.,ID=AT4G12120.1-Protein;Name=AT4G12120.1;Derive...
576,Chr4,7258111,7258237,4_801,Chr4,TAIR10,CDS,7258112,7258237,.,-,0,"Parent=AT4G12120.1,AT4G12120.1-Protein;"
577,Chr4,7258111,7258237,4_801,Chr4,TAIR10,exon,7258112,7258237,.,-,.,Parent=AT4G12120.1
578,Chr4,7255726,7269426,4_801,Chr4,TAIR10,chromosome,1,18585056,.,.,.,ID=Chr4;Name=Chr4

In [18]:
annot = annot[annot['attribute'].str.contains('protein_coding_gene')]

In [19]:
annot['gene_id'] = annot['attribute'].str.split(';').str[0].str.replace('ID=', '')

/tmp/ipykernel_2933107/2678680341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  annot['gene_id'] = annot['attribute'].str.split(';').str[0].str.replace('ID=', '')

In [22]:
annot[annot['block_id'] == '4_801']['gene_id'].values

array(['AT4G12110', 'AT4G12130', 'AT4G12140', 'AT4G12150', 'AT4G12120'],
      dtype=object)

In [110]:
sign_blocks_union_first_last_gen = sign_blocks_union_first_last_gen.merge(annot, left_on = 'block', right_on = 'block_id')

In [119]:
sign_blocks_union_first_last_gen

,block,model,gen,block_chrom,block_start,block_end,block_id,gene_chrom,source,feature,gene_start,gene_end,score,strand,frame,attribute,gene_id
0,1_1318,wza_lfmm_f,first_gen,Chr1,9219501,9221073,1_1318,Chr1,TAIR10,gene,9219463,9223649,.,+,.,ID=AT1G26680;Note=protein_coding_gene;Name=AT1...,AT1G26680
1,1_1594,wza_lfmm_f,first_gen,Chr1,10898171,10898797,1_1594,Chr1,TAIR10,gene,10898172,10899912,.,+,.,ID=AT1G30720;Note=protein_coding_gene;Name=AT1...,AT1G30720
2,1_1594,wza_lfmm_f,first_gen,Chr1,10895628,10897109,1_1594,Chr1,TAIR10,gene,10895280,10897109,.,+,.,ID=AT1G30710;Note=protein_coding_gene;Name=AT1...,AT1G30710
3,1_485,wza_lfmm_f,first_gen,Chr1,3995653,3997907,1_485,Chr1,TAIR10,gene,3995169,3997907,.,+,.,ID=AT1G11840;Note=protein_coding_gene;Name=AT1...,AT1G11840
4,1_4899,wza_lfmm_f,first_gen,Chr1,26838288,26841490,1_4899,Chr1,TAIR10,gene,26838289,26841490,.,-,.,ID=AT1G71210;Note=protein_coding_gene;Name=AT1...,AT1G71210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,4_3051,wza_binom_reg_l,last_gen,Chr4,18372673,18374204,4_3051,Chr4,TAIR10,gene,18370968,18374204,.,-,.,ID=AT4G39520;Note=protein_coding_gene;Name=AT4...,AT4G39520
244,4_3051,wza_binom_reg_l,last_gen,Chr4,18374735,18377240,4_3051,Chr4,TAIR10,gene,18374736,18377240,.,-,.,ID=AT4G39530;Note=protein_coding_gene;Name=AT4...,AT4G39530
245,4_3051,wza_binom_reg_l,last_gen,Chr4,18378224,18378453,4_3051,Chr4,TAIR10,gene,18378225,18380417,.,+,.,ID=AT4G39540;Note=protein_coding_gene;Name=AT4...,AT4G39540
246,5_687,wza_binom_reg_l,last_gen,Chr5,8162520,8162914,5_687,Chr5,TAIR10,gene,8162213,8164066,.,+,.,ID=AT5G24130;Note=protein_coding_gene;Name=AT5...,AT5G24130
247,5_707,wza_binom_reg_l,last_gen,Chr5,8285241,8285955,5_707,Chr5,TAIR10,gene,8284436,8288039,.,-,.,ID=AT5G24320;Note=protein_coding_gene;Name=AT5...,AT5G24320

In [112]:
sign_blocks_union_first_last_gen.to_csv('gene_and_model_sign_blocks_union_first_last_gen_BH.csv')

In [21]:
# Assuming your DataFrame has a column for gene IDs, e.g., 'gene_id'
gene_ids = annot['gene_id'].unique()  # Get unique gene IDs

# Write these gene IDs to a file to use for filtering the GFF3 file
with open(gene_ids_file, 'w') as f:
    for gene_id in gene_ids:
        f.write(f"{gene_id}\n")
        
print("Gene IDs saved to gene_ids.txt")

Gene IDs saved to gene_ids.txt

In [24]:
gene_ids

    AT1G71210
0   AT1G71220
1   AT1G71235
2   AT1G71240
3   AT1G71250
4   AT1G71260
..        ...
82  AT1G04220
83  AT1G04120
84  AT1G04150
85  AT1G04170
86  AT1G04050

[87 rows x 1 columns]

In [32]:
gene_ids = pd.read_csv(gene_ids_file)

In [33]:
gene_ids

    AT1G71210
0   AT1G71220
1   AT1G71235
2   AT1G71240
3   AT1G71250
4   AT1G71260
..        ...
82  AT1G04220
83  AT1G04120
84  AT1G04150
85  AT1G04170
86  AT1G04050

[87 rows x 1 columns]

In [26]:
# Step 2: Filter the GFF3 file using the list of gene IDs
filter_cmd = f"grep -Ff {gene_ids_file} ../key_files/TAIR10_GFF3_genes_transposons.gff > {gff_filtered_file}"
subprocess.run(filter_cmd, shell=True, check=True)

CompletedProcess(args='grep -Ff sign_blocks_union_first_last_gen_gene_ids.txt ../key_files/TAIR10_GFF3_genes_transposons.gff > sign_blocks_union_first_last_gen.gff', returncode=0)

In [27]:
# Define a function to replace chromosome names in the GFF file
def replace_chromosomes(gff_file):
    # Read the GFF file
    with open(gff_file, 'r') as file:
        gff_content = file.read()
    
    # Replace Chr1, Chr2, ..., with 1, 2, ..., and leave ChrC and ChrM unchanged
    gff_content = gff_content.replace('Chr1', '1')
    gff_content = gff_content.replace('Chr2', '2')
    gff_content = gff_content.replace('Chr3', '3')
    gff_content = gff_content.replace('Chr4', '4')
    gff_content = gff_content.replace('Chr5', '5')
    # ChrC and ChrM remain unchanged, no need for replacements
    
    # Write the modified content back to the GFF file
    with open(gff_file, 'w') as file:
        file.write(gff_content)

# Specify your GFF file
gff_file = gff_filtered_file

# Call the function to replace chromosome names
replace_chromosomes(gff_file)

print("Chromosome names replaced successfully.")

Chromosome names replaced successfully.

In [29]:
# Step 3: Use gffread to extract sequences
gffread_cmd = f"""
module load GffRead/0.12.3; \
gffread -w {nucleotide_seq_sign_genes} -g ../key_files/arabidopsis_reference/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa {gff_file}
"""

subprocess.run(gffread_cmd, shell=True, check=True, executable="/bin/bash")
print("Nucleotide sequences saved to output_transcripts.fa")

Nucleotide sequences saved to output_transcripts.fa

In [ ]:
# conda activate /home/tbellagio/miniforge3/envs/diamond_env

In [ ]:
pd.read_csv()

In [ ]:
diamond blastx -d nr_diamond_db \
-q /carnegie/nobackup/scratch/tbellagio/gea_grene-net/signficant_intersection/sign_blocks_union_first_last_gen_nucleotide_seq.fa \
-o sign_blocks_union_first_last_gen_prots.out \
--threads 8 \
--outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle

In [30]:
!pwd -P

/carnegie/nobackup/scratch/tbellagio/gea_grene-net/signficant_intersection

In [31]:
'/carnegie/nobackup/scratch/tbellagio/gea_grene-net/signficant_intersection/nucleotide_seq_genes_lfmm_wza_bio1_sign_blocks.fa'

'/carnegie/nobackup/scratch/tbellagio/gea_grene-net/signficant_intersection/nucleotide_seq_genes_lfmm_wza_bio1_sign_blocks.fa'

In [ ]:
#diamond blastx -d nr_diamond_db -q /carnegie/nobackup/scratch/tbellagio/gea_grene-net/signficant_intersection/nucleotide_seq_genes_lfmm_wza_bio1_sign_blocks.fa -o seq_genes_lfmm_wza_bio1_sign_blocks_note.out --threads 8 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle

In [4]:
column_names = [
    "qseqid",    # Query sequence ID
    "sseqid",    # Subject sequence ID
    "pident",    # Percentage of identical matches
    "length",    # Alignment length
    "mismatch",  # Number of mismatches
    "gapopen",   # Number of gap openings
    "qstart",    # Start of alignment in query
    "qend",      # End of alignment in query
    "sstart",    # Start of alignment in subject
    "send",      # End of alignment in subject
    "evalue",    # Expectation value (E-value)
    "bitscore",  # Bit score
    "stitle"     # Subject title (description of the hit)
]

In [7]:
# Function to count the number of sequences in a FASTA file

def count_fasta_sequences(file_path):
    genes_blasted = []
    count = 0
    with open(file_path, 'r') as f:
        for line in f:
            if line.startswith(">"):
                gene = line.split(' ')[0]
                genes_blasted.append(gene.replace('>', ''))
                count += 1
    return genes_blasted

In [8]:
isoforms_blasted = count_fasta_sequences('nucleotide_seq_genes_lfmm_wza_bio1_sign_blocks.fa')

In [5]:
blastx_rs = pd.read_csv('/carnegie/nobackup/scratch/tbellagio/blast_protein_db/seq_genes_lfmm_wza_bio1_sign_blocks_note.out', sep = '\t',header=None)
blastx_rs.columns = column_names

In [10]:
missing_isoforms = set(isoforms_blasted) - set(blastx_rs['qseqid'])

In [11]:
missing_isoforms

set()

In [14]:
blastx_rs['qseqid'].nunique()

245

In [17]:
# Group by qseqid and keep the row with the max bitscore for each qseqid
blastx_rs = blastx_rs.loc[blastx_rs.groupby('qseqid')['bitscore'].idxmax()]

# Reset index if necessary
blastx_rs = blastx_rs.reset_index(drop=True)

In [18]:
blastx_rs

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,stitle
0,AT1G11840.1,CAA0192913.1,100.0,293,0,0,69,947,4,296,1.860000e-210,591.0,CAA0192913.1 unnamed protein product [Arabidop...
1,AT1G11840.2,CAA0192913.1,99.7,288,1,0,292,1155,9,296,1.680000e-205,582.0,CAA0192913.1 unnamed protein product [Arabidop...
2,AT1G11840.3,CAA0192913.1,100.0,284,0,0,60,911,13,296,1.230000e-204,576.0,CAA0192913.1 unnamed protein product [Arabidop...
3,AT1G11840.4,NP_001184968.1,98.0,301,6,0,32,934,22,322,6.210000e-211,593.0,NP_001184968.1 glyoxalase/bleomycin resistance...
4,AT1G11840.5,NP_001031026.1,100.0,232,0,0,307,1002,1,232,1.830000e-163,472.0,NP_001031026.1 glyoxalase/bleomycin resistance...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,AT5G60360.1,NP_568921.1,100.0,358,0,0,148,1221,1,358,2.570000e-261,725.0,NP_568921.1 aleurain-like protease [Arabidopsi...
241,AT5G60360.2,NP_001032106.1,100.0,357,0,0,148,1218,1,357,1.950000e-260,723.0,NP_001032106.1 aleurain-like protease [Arabido...
242,AT5G60360.3,NP_001078774.1,100.0,361,0,0,148,1230,1,361,1.150000e-265,736.0,NP_001078774.1 aleurain-like protease [Arabido...
243,AT5G60370.1,NP_200845.1,100.0,413,0,0,21,1259,1,413,1.440000e-291,805.0,NP_200845.1 exonuclease V-like protein [Arabid...
244,AT5G60380.1,NP_200846.1,100.0,373,0,0,1,1119,1,373,1.200000e-281,772.0,"NP_200846.1 transmembrane protein, putative (D..."

In [19]:
# AT2G27030 is cam5

In [20]:
blastx_rs[blastx_rs['qseqid'].str.contains('AT2G27030')]

,qseqid,sseqid,pident,length,mismatch,gapopen,qstart,qend,sstart,send,evalue,bitscore,stitle
133,AT2G27030.1,KAH9675065.1,95.6,158,7,0,39,512,2,159,7.000000e-79,245.0,KAH9675065.1 calmodulin-7 [Citrus sinensis]
134,AT2G27030.2,CAF1700968.1,97.7,128,3,0,668,1051,5,132,1.350000e-55,198.0,CAF1700968.1 unnamed protein product [Brassica...
135,AT2G27030.3,NP_850097.1,100.0,181,0,0,66,608,1,181,4.160000e-100,300.0,NP_850097.1 calmodulin 5 [Arabidopsis thaliana]

In [34]:
blastx_rs['qseqid'].to_csv('founds_panther.csv',index=None, header=None,sep = ',')

In [104]:
# Step 2: Apply the function to df_genes to create a new column with the matching gene_id from tair
sign_wza_lfmm['matching_gene_id'] = sign_wza_lfmm.apply(lambda row: match_gene_id(row, tair), axis=1)

/tmp/ipykernel_4033925/243824316.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sign_wza_lfmm['matching_gene_id'] = sign_wza_lfmm.apply(lambda row: match_gene_id(row, tair), axis=1)

In [105]:
sign_wza_lfmm

,block,SNPs,hits,Z,top_candidate_p,Z_pVal,matching_gene_id
350,1_1318,44,22,13.132881,1.703152e-32,5.361920e-08,AT1G26680
654,1_1594,30,15,12.340603,1.346841e-22,1.942342e-08,"AT1G30710,AT1G30720"
2046,1_2867,64,12,12.798694,2.029109e-12,2.191944e-06,"AT1G55660,AT1G55670,AT1G55675,AT1G55680,AT1G55690"
3850,1_4505,96,9,17.562307,5.923819e-07,4.216780e-08,"AT1G67560,AT1G67570"
4126,1_4758,40,2,11.020971,6.073662e-02,2.316135e-06,AT1G70020
4227,1_485,36,3,12.925697,5.580758e-03,1.722963e-08,"AT1G11840,AT1G70580,AT1G70590,AT1G70600,AT1G70..."
4789,1_702,1699,267,12.236921,1.282245e-221,8.324132e-10,"AT1G17500,AT1G17510,AT1G17520,AT1G17530,AT1G17..."
5244,2_1116,26,22,10.800096,1.438617e-40,3.594995e-07,AT2G24230
5407,2_1265,16,15,11.151806,1.585000e-29,1.569795e-08,AT2G27030
7059,2_827,141,82,22.186910,1.602818e-124,8.449797e-09,"AT2G17380,AT2G17390,AT2G17410,AT2G17420"
7214,2_970,1716,55,12.847247,2.080748e-13,2.243761e-13,"AT2G22475,AT2G22480,AT2G22490,AT2G22500,AT2G22..."
7399,3_1136,24,9,10.000855,1.141790e-12,1.574742e-06,None
7614,3_133,40,8,13.741720,5.782126e-09,5.730219e-09,"AT3G05327,AT3G28580,AT3G28590,AT3G28600,AT3G28..."
7658,3_137,65,22,13.610011,8.035261e-28,6.002880e-07,"AT3G05380,AT3G05390,AT3G28910,AT3G28917,AT3G28..."
8884,3_250,38,9,11.374437,1.254594e-10,8.289905e-07,"AT3G07350,AT3G47390,AT3G47400,AT3G47410,AT3G47420"
9271,3_2855,48,6,14.343321,8.559985e-06,7.725087e-09,AT3G50750
9785,3_3325,53,1,12.259003,4.129632e-01,1.366619e-06,"AT3G62360,AT3G62370"
13384,4_801,225,130,23.960528,7.309601e-196,1.040595e-06,"AT4G12110,AT4G12120,AT4G12130,AT4G12140,AT4G12150"
14638,5_1947,215,59,23.067357,9.586678e-66,1.399768e-06,"AT5G44080,AT5G44090,AT5G44100,AT5G44110,AT5G44120"
14961,5_2244,39,14,13.843255,1.193361e-18,3.556710e-09,AT5G48560
15696,5_2922,1598,10,18.230969,9.570234e-01,1.710446e-07,"AT5G59820,AT5G59830,AT5G59840,AT5G59845,AT5G59..."
16421,5_780,40,14,11.961668,1.818823e-18,3.341260e-07,"AT5G26800,AT5G26805"

In [14]:
sign_wza_lfmm[sign_wza_lfmm['block'] == '2_1265']

,block,SNPs,hits,Z,top_candidate_p,Z_pVal,matching_gene_id
5407,2_1265,16,15,11.151806,1.585000e-29,1.569795e-08,AT2G27030

In [22]:
tair

,Unnamed: 0,chrom,gene_start,gene_end,gene_symbol,biotype,gene_id,exon_chromstart,exon_chromend,blocks
0,0,1,3631,5899,AT1G01010,protein_coding_gene,AT1G01010,"3631,3996,4486,4706,5174,5439","3913,4276,4605,5095,5326,5899",['1_0']
1,6,1,5928,8737,AT1G01020,protein_coding_gene,AT1G01020,"8571,8417,8236,7942,7762,7564,7384,7157,6437,5...","8737,8464,8325,7987,7835,7649,7450,7232,7069,6...",['1_0']
2,24,1,11649,13714,AT1G01030,protein_coding_gene,AT1G01030,"13335,11649","13714,13173",['1_0']
3,26,1,23146,31227,AT1G01040,protein_coding_gene,AT1G01040,"23146,24542,24752,25041,25524,25825,26081,2629...","24451,24655,24962,25435,25743,25997,26203,2645...",['1_0']
4,66,1,31170,33153,AT1G01050,protein_coding_gene,AT1G01050,"33029,32547,32431,32282,32088,31933,31693,3152...","33153,32670,32459,32347,32195,31998,31813,3160...",['1_0']
...,...,...,...,...,...,...,...,...,...,...
27201,207189,5,26959569,26960323,AT5G67600,protein_coding_gene,AT5G67600,"26960181,26959937,26959569","26960323,26960093,26959799",['5_3109']
27202,207192,5,26960931,26963638,AT5G67610,protein_coding_gene,AT5G67610,"26963509,26963122,26962863,26962648,26962503,2...","26963638,26963335,26963020,26962793,26962562,2...",['5_3109']
27203,207212,5,26964770,26965996,AT5G67620,protein_coding_gene,AT5G67620,"26965468,26965198,26964770","26965996,26965379,26965004",['5_3109']
27204,207215,5,26967381,26969394,AT5G67630,protein_coding_gene,AT5G67630,"26968558,26967381","26969394,26968195",['5_3109']
27205,207217,5,26969546,26970641,AT5G67640,protein_coding_gene,AT5G67640,"26970444,26970312,26969915,26969546","26970641,26970360,26970241,26969670",['5_3109']

In [15]:
sign_wza_lfmm

,block,SNPs,hits,Z,top_candidate_p,Z_pVal,matching_gene_id
350,1_1318,44,22,13.132881,1.703152e-32,5.361920e-08,AT1G26680
654,1_1594,30,15,12.340603,1.346841e-22,1.942342e-08,"AT1G30710,AT1G30720"
2046,1_2867,64,12,12.798694,2.029109e-12,2.191944e-06,"AT1G55660,AT1G55670,AT1G55675,AT1G55680,AT1G55690"
3850,1_4505,96,9,17.562307,5.923819e-07,4.216780e-08,"AT1G67560,AT1G67570"
4126,1_4758,40,2,11.020971,6.073662e-02,2.316135e-06,AT1G70020
4227,1_485,36,3,12.925697,5.580758e-03,1.722963e-08,"AT1G11840,AT1G70580,AT1G70590,AT1G70600,AT1G70..."
4789,1_702,1699,267,12.236921,1.282245e-221,8.324132e-10,"AT1G17500,AT1G17510,AT1G17520,AT1G17530,AT1G17..."
5244,2_1116,26,22,10.800096,1.438617e-40,3.594995e-07,AT2G24230
5407,2_1265,16,15,11.151806,1.585000e-29,1.569795e-08,AT2G27030
7059,2_827,141,82,22.186910,1.602818e-124,8.449797e-09,"AT2G17380,AT2G17390,AT2G17410,AT2G17420"
7214,2_970,1716,55,12.847247,2.080748e-13,2.243761e-13,"AT2G22475,AT2G22480,AT2G22490,AT2G22500,AT2G22..."
7399,3_1136,24,9,10.000855,1.141790e-12,1.574742e-06,None
7614,3_133,40,8,13.741720,5.782126e-09,5.730219e-09,"AT3G05327,AT3G28580,AT3G28590,AT3G28600,AT3G28..."
7658,3_137,65,22,13.610011,8.035261e-28,6.002880e-07,"AT3G05380,AT3G05390,AT3G28910,AT3G28917,AT3G28..."
8884,3_250,38,9,11.374437,1.254594e-10,8.289905e-07,"AT3G07350,AT3G47390,AT3G47400,AT3G47410,AT3G47420"
9271,3_2855,48,6,14.343321,8.559985e-06,7.725087e-09,AT3G50750
9785,3_3325,53,1,12.259003,4.129632e-01,1.366619e-06,"AT3G62360,AT3G62370"
13384,4_801,225,130,23.960528,7.309601e-196,1.040595e-06,"AT4G12110,AT4G12120,AT4G12130,AT4G12140,AT4G12150"
14638,5_1947,215,59,23.067357,9.586678e-66,1.399768e-06,"AT5G44080,AT5G44090,AT5G44100,AT5G44110,AT5G44120"
14961,5_2244,39,14,13.843255,1.193361e-18,3.556710e-09,AT5G48560
15696,5_2922,1598,10,18.230969,9.570234e-01,1.710446e-07,"AT5G59820,AT5G59830,AT5G59840,AT5G59845,AT5G59..."
16421,5_780,40,14,11.961668,1.818823e-18,3.341260e-07,"AT5G26800,AT5G26805"

In [51]:
# Function to retrieve gene information from Ensembl
def get_gene_info(gene_id):
    base_url = f"https://rest.ensembl.org/lookup/symbol/{gene_id}"
    headers = {"Content-Type": "application/json"}
    
    # Send the request
    response = requests.get(base_url, headers=headers)
    
    # Check if the request was successful
    if response.status_code == 200:
        return response.json()  # Return the JSON response
    else:
        return None  # Return None if the request failed

In [52]:
get_gene_info('AT2G27030')

In [24]:
import requests
import pandas as pd

# Function to retrieve gene information from Ensembl
def get_gene_info(gene_id):
    base_url = f"https://rest.ensembl.org/lookup/symbol/arabidopsis_thaliana/{gene_id}"
    headers = {"Content-Type": "application/json"}
    
    # Send the request
    response = requests.get(base_url, headers=headers)
    
    # Check if the request was successful
    if response.status_code == 200:
        return response.json()  # Return the JSON response
    else:
        return None  # Return None if the request failed

# Initialize an empty list to store gene information and the corresponding block
gene_info_list = []

# Loop over the rows of sign_wza_lfmm
for index, row in sign_wza_lfmm.iterrows():
    # Get the block and matching gene IDs from the row
    block = row['block']  # Assuming there's a column 'block' in your dataframe
    matching_gene_ids = row['matching_gene_id']  # List or comma-separated gene_ids
    
    # Skip rows where matching_gene_ids is empty or None
    if not matching_gene_ids:
        continue  # Skip this iteration if matching_gene_ids is None or empty
    
    # If matching_gene_ids is a string, split by commas into a list
    if isinstance(matching_gene_ids, str):
        matching_gene_ids = matching_gene_ids.split(',')
    
    # Loop through each gene_id and retrieve information from the API
    for gene_id in matching_gene_ids:
        gene_info = get_gene_info(gene_id.strip())  # Ensure any extra spaces are removed
        if gene_info:
            # Add the gene information and the corresponding block to the list
            gene_info_list.append({
                "block": block,
                "gene_id": gene_id,
                "gene_name": gene_info.get('display_name'),
                "start": gene_info.get('start'),
                "end": gene_info.get('end'),
                "biotype": gene_info.get('biotype'),
                "description": gene_info.get('description')
            })

In [118]:
sign_wza_lfmm

,block,SNPs,hits,Z,top_candidate_p,Z_pVal,matching_gene_id
350,1_1318,44,22,13.132881,1.703152e-32,5.361920e-08,AT1G26680
654,1_1594,30,15,12.340603,1.346841e-22,1.942342e-08,"AT1G30710,AT1G30720"
2046,1_2867,64,12,12.798694,2.029109e-12,2.191944e-06,"AT1G55660,AT1G55670,AT1G55675,AT1G55680,AT1G55690"
3850,1_4505,96,9,17.562307,5.923819e-07,4.216780e-08,"AT1G67560,AT1G67570"
4126,1_4758,40,2,11.020971,6.073662e-02,2.316135e-06,AT1G70020
4227,1_485,36,3,12.925697,5.580758e-03,1.722963e-08,"AT1G11840,AT1G70580,AT1G70590,AT1G70600,AT1G70..."
4789,1_702,1699,267,12.236921,1.282245e-221,8.324132e-10,"AT1G17500,AT1G17510,AT1G17520,AT1G17530,AT1G17..."
5244,2_1116,26,22,10.800096,1.438617e-40,3.594995e-07,AT2G24230
5407,2_1265,16,15,11.151806,1.585000e-29,1.569795e-08,AT2G27030
7059,2_827,141,82,22.186910,1.602818e-124,8.449797e-09,"AT2G17380,AT2G17390,AT2G17410,AT2G17420"
7214,2_970,1716,55,12.847247,2.080748e-13,2.243761e-13,"AT2G22475,AT2G22480,AT2G22490,AT2G22500,AT2G22..."
7399,3_1136,24,9,10.000855,1.141790e-12,1.574742e-06,None
7614,3_133,40,8,13.741720,5.782126e-09,5.730219e-09,"AT3G05327,AT3G28580,AT3G28590,AT3G28600,AT3G28..."
7658,3_137,65,22,13.610011,8.035261e-28,6.002880e-07,"AT3G05380,AT3G05390,AT3G28910,AT3G28917,AT3G28..."
8884,3_250,38,9,11.374437,1.254594e-10,8.289905e-07,"AT3G07350,AT3G47390,AT3G47400,AT3G47410,AT3G47420"
9271,3_2855,48,6,14.343321,8.559985e-06,7.725087e-09,AT3G50750
9785,3_3325,53,1,12.259003,4.129632e-01,1.366619e-06,"AT3G62360,AT3G62370"
13384,4_801,225,130,23.960528,7.309601e-196,1.040595e-06,"AT4G12110,AT4G12120,AT4G12130,AT4G12140,AT4G12150"
14638,5_1947,215,59,23.067357,9.586678e-66,1.399768e-06,"AT5G44080,AT5G44090,AT5G44100,AT5G44110,AT5G44120"
14961,5_2244,39,14,13.843255,1.193361e-18,3.556710e-09,AT5G48560
15696,5_2922,1598,10,18.230969,9.570234e-01,1.710446e-07,"AT5G59820,AT5G59830,AT5G59840,AT5G59845,AT5G59..."
16421,5_780,40,14,11.961668,1.818823e-18,3.341260e-07,"AT5G26800,AT5G26805"

In [25]:
# Convert the gene information list to a DataFrame for further analysis
df_gene_info_ensembl = pd.DataFrame(gene_info_list)

In [26]:
df_gene_info_ensembl

,block,gene_id,gene_name,start,end,biotype,description
0,1_1318,AT1G26680,AT1G26680,9219460,9223795,protein_coding,transcriptional factor B3 family protein [Sour...
1,1_1594,AT1G30710,AT1G30710,10895252,10897127,protein_coding,FAD-binding Berberine family protein [Source:N...
2,1_1594,AT1G30720,AT1G30720,10897925,10899975,protein_coding,FAD-binding Berberine family protein [Source:N...
3,1_2867,AT1G55660,AT1G55660,20800694,20802377,protein_coding,"FBD, F-box and Leucine Rich Repeat domains con..."
4,1_2867,AT1G55675,AT1G55675,20803661,20804574,protein_coding,transmembrane protein [Source:NCBI gene (forme...
...,...,...,...,...,...,...,...
116,5_2922,AT5G60335,AT5G60335,24272995,24274860,protein_coding,hydroxyacyl-thioester dehydratase type-like pr...
117,5_2922,AT5G60350,AT5G60350,24277730,24279147,protein_coding,None
118,5_2922,AT5G60370,AT5G60370,24282666,24285061,protein_coding,exonuclease V-like protein [Source:NCBI gene (...
119,5_2922,AT5G60380,AT5G60380,24285920,24287808,protein_coding,"transmembrane protein, putative (DUF239) [Sour..."
120,5_780,AT5G26805,AT5G26805,9427543,9428067,protein_coding,B3 domain protein [Source:NCBI gene (formerly ...

In [1]:
from biomart import BiomartServer

ModuleNotFoundError: No module named 'biomart'

In [1]:
# Example using BioMart to map gene IDs between Ensembl and RefSeq
import biomart

# Connect to the Ensembl Plants BioMart database
server = biomart.BioMartServer("http://plants.ensembl.org/biomart")

# Use the appropriate dataset for Arabidopsis thaliana
dataset = server.datasets['athaliana_eg_gene']

# Query to map TAIR ID to RefSeq ID
response = dataset.search({
    'filters': {
        'ensembl_gene_id': ['AT2G27030']  # TAIR ID or Ensembl ID
    },
    'attributes': [
        'ensembl_gene_id', 'external_gene_name', 'refseq_mrna', 'refseq_peptide'
    ]
})

print(response.text)  # This will show the mapped gene IDs

ModuleNotFoundError: No module named 'biomart'

In [ ]:
"https://rest.ensembl.org/lookup/symbol/arabidopsis_thaliana/AT2G27030"

In [69]:
def get_gene_info(gene_id):
    base_url = f"https://rest.ensembl.org/lookup/symbol/arabidopsis_thaliana/{gene_id}"
    headers = {"Content-Type": "application/json"}
    
    # Send the request
    response = requests.get(base_url, headers=headers)
    
    # Check if the request was successful
    if response.status_code == 200:
        return response.json()  # Return the JSON response
    else:
        return None  # Return None if the request failed

In [87]:
curl -X GET "https://api.ncbi.nlm.nih.gov/datasets/v2alpha/gene/id/AT2G27030/download_summary" \
 -H "accept: application/json"

SyntaxError: invalid syntax (440813899.py, line 1)

In [85]:
gene_id = 'AT2G27030'
gene_info = get_gene_info(gene_id.strip())  # Ensure any extra spaces are removed

In [86]:
print(gene_info)

None

In [70]:
get_gene_info('AT2G27030')

In [61]:
df_gene_info = pd.DataFrame(gene_info_list)

In [46]:
tair[tair['gene_id']== 'AT2G27030']

,Unnamed: 0,chrom,gene_start,gene_end,gene_symbol,biotype,gene_id,exon_chromstart,exon_chromend,blocks
9060,69982,2,11532004,11534333,AT2G27030,protein_coding_gene,AT2G27030,"11532004,11532687,11532007,11532004,11532687,1...","11532144,11533276,11534272,11532144,11533056,1...","['2_1264', '2_1265', '2_1266']"

In [ ]:
AT2G27030

In [68]:
df_gene_info[df_gene_info['gene_id'] == 'AT2G27030']

Empty DataFrame
Columns: [block, gene_id, gene_name, start, end, biotype, description]
Index: []

In [63]:
df_gene_info.to_csv('blocks_annotation_wza_results_lfmm_bio1.csv',index =None)

In [19]:
dict_blocks['1_1594'][-1] # 1_10895628  1_10898797

'1_10898797'

In [120]:
sign_blocks_union_first_last_gen

,block,model,gen,block_chrom,block_start,block_end,block_id,gene_chrom,source,feature,gene_start,gene_end,score,strand,frame,attribute,gene_id
0,1_1318,wza_lfmm_f,first_gen,Chr1,9219501,9221073,1_1318,Chr1,TAIR10,gene,9219463,9223649,.,+,.,ID=AT1G26680;Note=protein_coding_gene;Name=AT1...,AT1G26680
1,1_1594,wza_lfmm_f,first_gen,Chr1,10898171,10898797,1_1594,Chr1,TAIR10,gene,10898172,10899912,.,+,.,ID=AT1G30720;Note=protein_coding_gene;Name=AT1...,AT1G30720
2,1_1594,wza_lfmm_f,first_gen,Chr1,10895628,10897109,1_1594,Chr1,TAIR10,gene,10895280,10897109,.,+,.,ID=AT1G30710;Note=protein_coding_gene;Name=AT1...,AT1G30710
3,1_485,wza_lfmm_f,first_gen,Chr1,3995653,3997907,1_485,Chr1,TAIR10,gene,3995169,3997907,.,+,.,ID=AT1G11840;Note=protein_coding_gene;Name=AT1...,AT1G11840
4,1_4899,wza_lfmm_f,first_gen,Chr1,26838288,26841490,1_4899,Chr1,TAIR10,gene,26838289,26841490,.,-,.,ID=AT1G71210;Note=protein_coding_gene;Name=AT1...,AT1G71210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,4_3051,wza_binom_reg_l,last_gen,Chr4,18372673,18374204,4_3051,Chr4,TAIR10,gene,18370968,18374204,.,-,.,ID=AT4G39520;Note=protein_coding_gene;Name=AT4...,AT4G39520
244,4_3051,wza_binom_reg_l,last_gen,Chr4,18374735,18377240,4_3051,Chr4,TAIR10,gene,18374736,18377240,.,-,.,ID=AT4G39530;Note=protein_coding_gene;Name=AT4...,AT4G39530
245,4_3051,wza_binom_reg_l,last_gen,Chr4,18378224,18378453,4_3051,Chr4,TAIR10,gene,18378225,18380417,.,+,.,ID=AT4G39540;Note=protein_coding_gene;Name=AT4...,AT4G39540
246,5_687,wza_binom_reg_l,last_gen,Chr5,8162520,8162914,5_687,Chr5,TAIR10,gene,8162213,8164066,.,+,.,ID=AT5G24130;Note=protein_coding_gene;Name=AT5...,AT5G24130
247,5_707,wza_binom_reg_l,last_gen,Chr5,8285241,8285955,5_707,Chr5,TAIR10,gene,8284436,8288039,.,-,.,ID=AT5G24320;Note=protein_coding_gene;Name=AT5...,AT5G24320

In [114]:
sign_blocks_union_first_last_gen['gene_id']

0      AT1G26680
1      AT1G30720
2      AT1G30710
3      AT1G11840
4      AT1G71210
         ...
243    AT4G39520
244    AT4G39530
245    AT4G39540
246    AT5G24130
247    AT5G24320
Name: gene_id, Length: 248, dtype: object

In [125]:
bonferroni = pd.read_csv('gene_and_model_sign_blocks_union_first_last_gen.csv')

false_disc = pd.read_csv('gene_and_model_sign_blocks_union_first_last_gen_BH.csv')

In [128]:
bonferroni

,Unnamed: 0,block,model,gen,block_chrom,block_start,block_end,block_id,gene_chrom,source,feature,gene_start,gene_end,score,strand,frame,attribute,gene_id
0,0,1_4899,wza_lfmm_f,first_gen,Chr1,26838288,26841490,1_4899,Chr1,TAIR10,gene,26838289,26841490,.,-,.,ID=AT1G71210;Note=protein_coding_gene;Name=AT1...,AT1G71210
1,1,1_4899,wza_lfmm_f,first_gen,Chr1,26841629,26851919,1_4899,Chr1,TAIR10,gene,26841630,26851919,.,+,.,ID=AT1G71220;Note=protein_coding_gene;Name=AT1...,AT1G71220
2,2,1_4899,wza_lfmm_f,first_gen,Chr1,26854558,26855222,1_4899,Chr1,TAIR10,gene,26854559,26855222,.,+,.,ID=AT1G71235;Note=protein_coding_gene;Name=AT1...,AT1G71235
3,3,1_4899,wza_lfmm_f,first_gen,Chr1,26855429,26859741,1_4899,Chr1,TAIR10,gene,26855430,26859741,.,+,.,ID=AT1G71240;Note=protein_coding_gene;Name=AT1...,AT1G71240
4,4,1_4899,wza_lfmm_f,first_gen,Chr1,26860117,26861726,1_4899,Chr1,TAIR10,gene,26860118,26861726,.,+,.,ID=AT1G71250;Note=protein_coding_gene;Name=AT1...,AT1G71250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,83,1_168,wza_binom_reg_l,last_gen,Chr1,1119698,1122526,1_168,Chr1,TAIR10,gene,1119699,1122526,.,-,.,ID=AT1G04220;Note=protein_coding_gene;Name=AT1...,AT1G04220
84,84,1_168,wza_binom_reg_l,last_gen,Chr1,1064449,1071047,1_168,Chr1,TAIR10,gene,1064450,1071047,.,-,.,ID=AT1G04120;Note=protein_coding_gene;Name=AT1...,AT1G04120
85,85,1_168,wza_binom_reg_l,last_gen,Chr1,1081207,1084246,1_168,Chr1,TAIR10,gene,1081208,1084246,.,-,.,ID=AT1G04150;Note=protein_coding_gene;Name=AT1...,AT1G04150
86,86,1_168,wza_binom_reg_l,last_gen,Chr1,1096945,1099898,1_168,Chr1,TAIR10,gene,1096946,1099898,.,+,.,ID=AT1G04170;Note=protein_coding_gene;Name=AT1...,AT1G04170
87,87,1_168,wza_binom_reg_l,last_gen,Chr1,1045597,1049297,1_168,Chr1,TAIR10,gene,1045598,1049297,.,-,.,ID=AT1G04050;Note=protein_coding_gene;Name=AT1...,AT1G04050

In [138]:
from Bio import Entrez

# Provide your email, NCBI requires this for queries
Entrez.email = "tbellg@berkeley.edu"

# Function to retrieve gene information using NCBI Entrez API
def get_gene_info_ncbi(gene_id):
    try:
        # Search for the gene in the NCBI database
        search_handle = Entrez.esearch(db="gene", term=f"{gene_id}[Gene]", retmax=1)
        search_results = Entrez.read(search_handle)
        search_handle.close()
        
        if search_results["IdList"]:
            gene_ncbi_id = search_results["IdList"][0]  # Get the first matching gene ID
            
            # Fetch detailed gene information using the gene ID
            fetch_handle = Entrez.efetch(db="gene", id=gene_ncbi_id, retmode="xml")
            gene_data = Entrez.read(fetch_handle)
            fetch_handle.close()
            
            # Extract relevant information from the gene data
            gene_info = gene_data[0]
            gene_name = gene_info['Entrezgene_gene']['Gene-ref']['Gene-ref_locus']
            gene_desc = gene_info['Entrezgene_summary']
            return {
                "gene_id": gene_id,
                "gene_name": gene_name,
                "description": gene_desc
            }
        else:
            return None
    except Exception as e:
        print(f"Error fetching data for gene {gene_id}: {e}")
        return None

# Initialize an empty list to store gene information and the corresponding block
gene_info_list = []
    # Loop through each gene_id and retrieve information from the API

for index,row in false_disc.iterrows():
    gene_id =  row['gene_id']
    block = row['block']
    print(gene_id)
    gene_info = get_gene_info_ncbi(gene_id.strip())  # Ensure any extra spaces are removed
    if gene_info:
        # Add the gene information and the corresponding block to the list
        gene_info_list.append({
            "block": block,
            "gene_id": gene_info.get('gene_id'),
            "gene_name": gene_info.get('gene_name'),
            "description": gene_info.get('description')
        })

AT1G26680
Error fetching data for gene AT1G26680: 'Gene-ref_locus'
AT1G30720
Error fetching data for gene AT1G30720: 'Gene-ref_locus'
AT1G30710
Error fetching data for gene AT1G30710: 'Gene-ref_locus'
AT1G11840
AT1G71210
Error fetching data for gene AT1G71210: 'Gene-ref_locus'
AT1G71220
AT1G71235
Error fetching data for gene AT1G71235: 'Gene-ref_locus'
AT1G71240
Error fetching data for gene AT1G71240: 'Gene-ref_locus'
AT1G71250
Error fetching data for gene AT1G71250: 'Gene-ref_locus'
AT1G71260
AT1G71280
Error fetching data for gene AT1G71280: 'Gene-ref_locus'
AT1G71290
Error fetching data for gene AT1G71290: 'Gene-ref_locus'
AT1G71300
Error fetching data for gene AT1G71300: 'Gene-ref_locus'
AT1G71310
AT1G71320
Error fetching data for gene AT1G71320: 'Gene-ref_locus'
AT1G71200
Error fetching data for gene AT1G71200: 'Gene-ref_locus'
AT1G71230
AT1G71270
AT1G17430
Error fetching data for gene AT1G17430: 'Gene-ref_locus'
AT1G17440
AT2G24230
Error fetching data for gene AT2G24230: 'Gene-ref_locus'
AT2G27030
AT2G02300
Error fetching data for gene AT2G02300: 'Entrezgene_summary'
AT2G17390
AT2G17410
Error fetching data for gene AT2G17410: 'Gene-ref_locus'
AT2G17420
AT2G17380
AT3G05327
Error fetching data for gene AT3G05327: 'Gene-ref_locus'
AT3G29035
AT3G50750
Error fetching data for gene AT3G50750: 'Entrezgene_summary'
AT4G16670
Error fetching data for gene AT4G16670: 'Gene-ref_locus'
AT4G34230
AT4G34240
AT4G34250
AT4G34265
Error fetching data for gene AT4G34265: 'Gene-ref_locus'
AT4G34270
Error fetching data for gene AT4G34270: 'Gene-ref_locus'
AT4G34272
Error fetching data for gene AT4G34272: 'Gene-ref_locus'
AT4G34280
Error fetching data for gene AT4G34280: 'Gene-ref_locus'
AT4G34290
Error fetching data for gene AT4G34290: 'Gene-ref_locus'
AT4G34300
Error fetching data for gene AT4G34300: 'Gene-ref_locus'
AT4G34320
Error fetching data for gene AT4G34320: 'Gene-ref_locus'
AT4G34330
Error fetching data for gene AT4G34330: 'Gene-ref_locus'
AT4G34340
Error fetching data for gene AT4G34340: 'Entrezgene_summary'
AT4G34350
AT4G34370
Error fetching data for gene AT4G34370: 'Entrezgene_summary'
AT4G34380
Error fetching data for gene AT4G34380: 'Gene-ref_locus'
AT4G34390
Error fetching data for gene AT4G34390: 'Entrezgene_summary'
AT4G34400
Error fetching data for gene AT4G34400: 'Gene-ref_locus'
AT4G34410
AT4G34412
Error fetching data for gene AT4G34412: 'Gene-ref_locus'
AT4G34419
Error fetching data for gene AT4G34419: 'Gene-ref_locus'
AT4G34420
Error fetching data for gene AT4G34420: 'Gene-ref_locus'
AT4G34430
AT4G34450
Error fetching data for gene AT4G34450: 'Gene-ref_locus'
AT4G34460
AT4G34470
Error fetching data for gene AT4G34470: 'Entrezgene_summary'
AT4G34490
AT4G34500
Error fetching data for gene AT4G34500: 'Gene-ref_locus'
AT4G34510
AT4G34520
AT4G34550
Error fetching data for gene AT4G34550: 'Gene-ref_locus'
AT4G34260
Error fetching data for gene AT4G34260: 'Entrezgene_summary'
AT4G34310
Error fetching data for gene AT4G34310: 'Gene-ref_locus'
AT4G34360
Error fetching data for gene AT4G34360: 'Gene-ref_locus'
AT4G34440
AT4G34480
Error fetching data for gene AT4G34480: 'Gene-ref_locus'
AT4G34530
AT4G34540
Error fetching data for gene AT4G34540: 'Gene-ref_locus'
AT4G12110
AT4G12130
Error fetching data for gene AT4G12130: 'Gene-ref_locus'
AT4G12140
Error fetching data for gene AT4G12140: 'Gene-ref_locus'
AT4G12150
Error fetching data for gene AT4G12150: 'Gene-ref_locus'
AT4G12120
AT5G44080
Error fetching data for gene AT5G44080: 'Gene-ref_locus'
AT5G44100
Error fetching data for gene AT5G44100: 'Entrezgene_summary'
AT5G44110
AT5G44120
AT5G44090
Error fetching data for gene AT5G44090: 'Gene-ref_locus'
AT5G46540
Error fetching data for gene AT5G46540: 'Entrezgene_summary'
AT5G48560
Error fetching data for gene AT5G48560: 'Gene-ref_locus'
AT5G22490
Error fetching data for gene AT5G22490: 'Gene-ref_locus'
AT1G27070
Error fetching data for gene AT1G27070: 'Gene-ref_locus'
AT1G33990
AT1G34000
AT1G34010
Error fetching data for gene AT1G34010: 'Gene-ref_locus'
AT1G34020
Error fetching data for gene AT1G34020: 'Gene-ref_locus'
AT1G34030
Error fetching data for gene AT1G34030: 'Gene-ref_locus'
AT1G33980
AT1G01450
Error fetching data for gene AT1G01450: 'Gene-ref_locus'
AT1G01450
Error fetching data for gene AT1G01450: 'Gene-ref_locus'
AT2G19110
AT3G44990
Error fetching data for gene AT3G44990: HTTP Error 400: Bad Request
AT3G49800
Error fetching data for gene AT3G49800: 'Gene-ref_locus'
AT3G49810
Error fetching data for gene AT3G49810: 'Gene-ref_locus'
AT3G53450
Error fetching data for gene AT3G53450: 'Entrezgene_summary'
AT4G18360
AT5G40050
Error fetching data for gene AT5G40050: 'Gene-ref_locus'
AT5G47510
Error fetching data for gene AT5G47510: 'Gene-ref_locus'
AT5G47520
Error fetching data for gene AT5G47520: 'Entrezgene_summary'
AT5G47530
Error fetching data for gene AT5G47530: 'Gene-ref_locus'
AT5G47550
Error fetching data for gene AT5G47550: 'Gene-ref_locus'
AT5G47560
AT5G47570
Error fetching data for gene AT5G47570: 'Gene-ref_locus'
AT5G47580
Error fetching data for gene AT5G47580: 'Entrezgene_summary'
AT5G47590
Error fetching data for gene AT5G47590: 'Gene-ref_locus'
AT5G47610
Error fetching data for gene AT5G47610: 'Gene-ref_locus'
AT5G47620
Error fetching data for gene AT5G47620: 'Gene-ref_locus'
AT5G47630
AT5G47635
Error fetching data for gene AT5G47635: 'Gene-ref_locus'
AT5G47640
Error fetching data for gene AT5G47640: 'Entrezgene_summary'
AT5G47650
AT5G47660
Error fetching data for gene AT5G47660: 'Gene-ref_locus'
AT5G47670
AT5G47690
Error fetching data for gene AT5G47690: 'Gene-ref_locus'
AT5G47700
Error fetching data for gene AT5G47700: 'Gene-ref_locus'
AT5G47710
Error fetching data for gene AT5G47710: 'Gene-ref_locus'
AT5G47730
Error fetching data for gene AT5G47730: 'Gene-ref_locus'
AT5G47740
Error fetching data for gene AT5G47740: HTTP Error 400: Bad Request
AT5G47750
Error fetching data for gene AT5G47750: 'Entrezgene_summary'
AT5G47760
AT5G47770
AT5G47790
Error fetching data for gene AT5G47790: 'Gene-ref_locus'
AT5G47800
Error fetching data for gene AT5G47800: 'Gene-ref_locus'
AT5G47810
Error fetching data for gene AT5G47810: 'Entrezgene_summary'
AT5G47820
AT5G47830
Error fetching data for gene AT5G47830: 'Gene-ref_locus'
AT5G47840
Error fetching data for gene AT5G47840: 'Entrezgene_summary'
AT5G47850
Error fetching data for gene AT5G47850: 'Entrezgene_summary'
AT5G47870
Error fetching data for gene AT5G47870: 'Entrezgene_summary'
AT5G47880
AT5G47540
Error fetching data for gene AT5G47540: 'Gene-ref_locus'
AT5G47600
Error fetching data for gene AT5G47600: 'Gene-ref_locus'
AT5G47680
AT5G47720
AT5G47780
AT5G47860
Error fetching data for gene AT5G47860: 'Gene-ref_locus'
AT1G23550
AT1G04020
AT1G04030
Error fetching data for gene AT1G04030: 'Gene-ref_locus'
AT1G04040
Error fetching data for gene AT1G04040: 'Gene-ref_locus'
AT1G04070
AT1G04080
Error fetching data for gene AT1G04080: 'Entrezgene_summary'
AT1G04090
Error fetching data for gene AT1G04090: 'Gene-ref_locus'
AT1G04100
AT1G04110
AT1G04130
AT1G04140
Error fetching data for gene AT1G04140: 'Gene-ref_locus'
AT1G04160
AT1G04171
Error fetching data for gene AT1G04171: 'Gene-ref_locus'
AT1G04180
Error fetching data for gene AT1G04180: 'Entrezgene_summary'
AT1G04190
AT1G04200
Error fetching data for gene AT1G04200: 'Gene-ref_locus'
AT1G04210
Error fetching data for gene AT1G04210: 'Gene-ref_locus'
AT1G04220
AT1G04120
AT1G04150
Error fetching data for gene AT1G04150: 'Gene-ref_locus'
AT1G04170
AT1G04050
AT1G05430
Error fetching data for gene AT1G05430: 'Gene-ref_locus'
AT1G45229
Error fetching data for gene AT1G45229: 'Gene-ref_locus'
AT1G45248
Error fetching data for gene AT1G45248: 'Gene-ref_locus'
AT1G45249
AT1G45233
AT1G09370
Error fetching data for gene AT1G09370: 'Gene-ref_locus'
AT4G14170
Error fetching data for gene AT4G14170: 'Gene-ref_locus'
AT4G14180
AT4G18890
Error fetching data for gene AT4G18890: 'Entrezgene_summary'
AT4G19230
AT4G27870
Error fetching data for gene AT4G27870: 'Gene-ref_locus'
AT5G45890
AT5G22280
Error fetching data for gene AT5G22280: 'Gene-ref_locus'
AT5G22290
AT5G25190
AT1G62790
Error fetching data for gene AT1G62790: 'Gene-ref_locus'
AT1G63930
Error fetching data for gene AT1G63930: 'Entrezgene_summary'
AT1G63940
Error fetching data for gene AT1G63940: 'Entrezgene_summary'
AT1G11925
Error fetching data for gene AT1G11925: 'Gene-ref_locus'
AT1G20570
Error fetching data for gene AT1G20570: 'Gene-ref_locus'
AT2G13150
Error fetching data for gene AT2G13150: 'Gene-ref_locus'
AT2G14620
Error fetching data for gene AT2G14620: 'Entrezgene_summary'
AT2G14635
Error fetching data for gene AT2G14635: 'Gene-ref_locus'
AT2G14660
Error fetching data for gene AT2G14660: 'Gene-ref_locus'
AT3G49810
Error fetching data for gene AT3G49810: 'Gene-ref_locus'
AT4G20325
Error fetching data for gene AT4G20325: 'Gene-ref_locus'
AT4G20330
Error fetching data for gene AT4G20330: 'Gene-ref_locus'
AT4G20340
Error fetching data for gene AT4G20340: 'Gene-ref_locus'
AT4G20350
Error fetching data for gene AT4G20350: 'Gene-ref_locus'
AT4G20360
Error fetching data for gene AT4G20360: 'Entrezgene_summary'
AT4G20370
AT4G20380
AT4G20320
Error fetching data for gene AT4G20320: 'Gene-ref_locus'
AT4G11720
Error fetching data for gene AT4G11720: HTTP Error 400: Bad Request
AT5G53030
Error fetching data for gene AT5G53030: 'Gene-ref_locus'
AT1G53940
AT1G21540
Error fetching data for gene AT1G21540: 'Gene-ref_locus'
AT3G48010
AT3G48020
Error fetching data for gene AT3G48020: 'Gene-ref_locus'
AT3G48030
Error fetching data for gene AT3G48030: 'Gene-ref_locus'
AT3G51320
Error fetching data for gene AT3G51320: 'Gene-ref_locus'
AT3G51325
Error fetching data for gene AT3G51325: 'Gene-ref_locus'
AT3G51330
Error fetching data for gene AT3G51330: 'Gene-ref_locus'
AT4G17850
Error fetching data for gene AT4G17850: 'Gene-ref_locus'
AT4G21910
Error fetching data for gene AT4G21910: 'Gene-ref_locus'
AT4G21920
Error fetching data for gene AT4G21920: 'Gene-ref_locus'
AT4G21926
Error fetching data for gene AT4G21926: 'Gene-ref_locus'
AT4G21930
Error fetching data for gene AT4G21930: 'Gene-ref_locus'
AT4G21940
AT4G21950
Error fetching data for gene AT4G21950: 'Gene-ref_locus'
AT4G21960
AT4G21970
Error fetching data for gene AT4G21970: 'Gene-ref_locus'
AT4G21980
AT4G21990
AT4G22000
Error fetching data for gene AT4G22000: 'Gene-ref_locus'
AT4G22010
Error fetching data for gene AT4G22010: 'Entrezgene_summary'
AT4G31600
AT4G31615
Error fetching data for gene AT4G31615: 'Gene-ref_locus'
AT4G31620
Error fetching data for gene AT4G31620: 'Gene-ref_locus'
AT4G31630
Error fetching data for gene AT4G31630: 'Gene-ref_locus'
AT4G31640
Error fetching data for gene AT4G31640: 'Gene-ref_locus'
AT4G31650
Error fetching data for gene AT4G31650: 'Gene-ref_locus'
AT4G31670
Error fetching data for gene AT4G31670: 'Entrezgene_summary'
AT4G31680
Error fetching data for gene AT4G31680: 'Gene-ref_locus'
AT4G31690
Error fetching data for gene AT4G31690: 'Gene-ref_locus'
AT4G31700
AT4G31720
AT4G31730
AT4G31740
Error fetching data for gene AT4G31740: 'Gene-ref_locus'
AT4G31750
AT4G31770
AT4G31610
AT4G31710
AT4G31760
Error fetching data for gene AT4G31760: 'Gene-ref_locus'
AT4G31660
Error fetching data for gene AT4G31660: 'Gene-ref_locus'
AT4G09012
Error fetching data for gene AT4G09012: 'Gene-ref_locus'
AT4G09020
AT4G10570
AT4G10560
Error fetching data for gene AT4G10560: 'Entrezgene_summary'
AT5G51690
AT1G44350
AT1G61360
Error fetching data for gene AT1G61360: 'Gene-ref_locus'
AT1G61370
Error fetching data for gene AT1G61370: 'Gene-ref_locus'
AT1G74448
Error fetching data for gene AT1G74448: 'Gene-ref_locus'
AT4G15290
AT4G39520
Error fetching data for gene AT4G39520: 'Gene-ref_locus'
AT4G39530
Error fetching data for gene AT4G39530: 'Gene-ref_locus'
AT4G39540
AT5G24130
Error fetching data for gene AT5G24130: 'Gene-ref_locus'
AT5G24320
Error fetching data for gene AT5G24320: 'Gene-ref_locus'

In [139]:
df_gene_info = pd.DataFrame(gene_info_list)

In [140]:
false_disc

,Unnamed: 0,block,model,gen,block_chrom,block_start,block_end,block_id,gene_chrom,source,feature,gene_start,gene_end,score,strand,frame,attribute,gene_id
0,0,1_1318,wza_lfmm_f,first_gen,Chr1,9219501,9221073,1_1318,Chr1,TAIR10,gene,9219463,9223649,.,+,.,ID=AT1G26680;Note=protein_coding_gene;Name=AT1...,AT1G26680
1,1,1_1594,wza_lfmm_f,first_gen,Chr1,10898171,10898797,1_1594,Chr1,TAIR10,gene,10898172,10899912,.,+,.,ID=AT1G30720;Note=protein_coding_gene;Name=AT1...,AT1G30720
2,2,1_1594,wza_lfmm_f,first_gen,Chr1,10895628,10897109,1_1594,Chr1,TAIR10,gene,10895280,10897109,.,+,.,ID=AT1G30710;Note=protein_coding_gene;Name=AT1...,AT1G30710
3,3,1_485,wza_lfmm_f,first_gen,Chr1,3995653,3997907,1_485,Chr1,TAIR10,gene,3995169,3997907,.,+,.,ID=AT1G11840;Note=protein_coding_gene;Name=AT1...,AT1G11840
4,4,1_4899,wza_lfmm_f,first_gen,Chr1,26838288,26841490,1_4899,Chr1,TAIR10,gene,26838289,26841490,.,-,.,ID=AT1G71210;Note=protein_coding_gene;Name=AT1...,AT1G71210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,243,4_3051,wza_binom_reg_l,last_gen,Chr4,18372673,18374204,4_3051,Chr4,TAIR10,gene,18370968,18374204,.,-,.,ID=AT4G39520;Note=protein_coding_gene;Name=AT4...,AT4G39520
244,244,4_3051,wza_binom_reg_l,last_gen,Chr4,18374735,18377240,4_3051,Chr4,TAIR10,gene,18374736,18377240,.,-,.,ID=AT4G39530;Note=protein_coding_gene;Name=AT4...,AT4G39530
245,245,4_3051,wza_binom_reg_l,last_gen,Chr4,18378224,18378453,4_3051,Chr4,TAIR10,gene,18378225,18380417,.,+,.,ID=AT4G39540;Note=protein_coding_gene;Name=AT4...,AT4G39540
246,246,5_687,wza_binom_reg_l,last_gen,Chr5,8162520,8162914,5_687,Chr5,TAIR10,gene,8162213,8164066,.,+,.,ID=AT5G24130;Note=protein_coding_gene;Name=AT5...,AT5G24130
247,247,5_707,wza_binom_reg_l,last_gen,Chr5,8285241,8285955,5_707,Chr5,TAIR10,gene,8284436,8288039,.,-,.,ID=AT5G24320;Note=protein_coding_gene;Name=AT5...,AT5G24320

In [143]:
false_disc.merge(df_gene_info, on = 'gene_id')[['block_id', 'model', 'gen', 'source', 'gene_name', 'description']].to_csv('genes_info_BH_tair10.csv',index=None)

In [137]:
#bonferroni.merge(df_gene_info, on = 'gene_id')[['block_id', 'model', 'gen', 'source', 'gene_name', 'description']].to_csv('genes_info_bonferronicor_tair10.csv',index=None)

In [118]:
df_gene_info.to_csv('genes_info_blocks_first_last_BHcorr_pre_blast.csv')

In [77]:
flowering_gene_ids = ['AT1G65480',  # FT
                      'AT1G74930',  # FLC
                      'AT1G04810',  # SOC1
                      'AT1G69120',  # AP1
                      'AT5G02470',  # FUL
                      'AT5G01330',  # LFY
                      'AT3G10040',  # AP2
                      'AT4G02560']  # SVP

In [78]:
sign_wza_lfmm

NameError: name 'sign_wza_lfmm' is not defined

In [120]:
df_gene_info_ncbi

,block,gene_id,gene_name,description
0,1_2867,AT1G55670,PSAG,"Encodes subunit G of photosystem I, an 11-kDa ..."
1,1_485,AT1G11840,GLX1,Encodes a glyoxalase I homolog ATGLX1.
2,1_485,AT1G70580,AOAT2,Encodes a protein with glyoxylate aminotransfe...
3,1_485,AT1G70610,ABCB26,member of TAP subfamily
4,1_485,AT1G70660,MMZ2,MMZ2/UEV1B encodes a protein that may play a r...
...,...,...,...,...
59,5_2922,AT5G60220,TET4,Member of TETRASPANIN family
60,5_2922,AT5G60230,SEN2,putative subunit of tRNA splicing endonuclease
61,5_2922,AT5G60300,LecRK-I.9,Lectin Receptor Kinase involved in protein-pro...
62,5_2922,AT5G60340,AAK6,Encodes a nuclear adenylate kinase that intera...
63,5_2922,AT5G60360,ALP,Encodes a senescence-associated thiol protease.

In [107]:
df_gene_info_ncbi = df_gene_info.copy()

In [109]:
df_gene_info_ncbi.to_csv('df_lfmm_wza_block_gene_info_ncbi.csv',index=None)

In [114]:
df_gene_info_ncbi['block'].unique()

array(['1_2867', '1_485', '1_702', '2_1265', '2_827', '2_970', '3_137',
       '3_250', '4_801', '5_1947', '5_2922'], dtype=object)

In [121]:
['1_485', '1_702', '1_2867', '2_827', '2_970','2_1265', '3_137',
       '3_250', '4_801', '5_1947', '5_2922']

['1_485',
 '1_702',
 '1_2867',
 '2_827',
 '2_970',
 '2_1265',
 '3_137',
 '3_250',
 '4_801',
 '5_1947',
 '5_2922']

In [123]:
for i in ['1_485', '1_702', '1_2867', '2_827', '2_970','2_1265', '3_137',
       '3_250', '4_801', '5_1947', '5_2922']:
    print(i)
    print(dict_blocks[i][0])
    print(dict_blocks[i][-1])

1_485
1_3995653
1_3997916
1_702
1_6018870
1_6181134
1_2867
1_20800345
1_20814896
2_827
2_7553538
2_7567816
2_970
2_9540996
2_9714921
2_1265
2_11533904
2_11534263
3_137
3_1540490
3_1548153
3_250
3_2346807
3_2350128
4_801
4_7255726
4_7269426
5_1947
5_17738817
5_17759685
5_2922
5_24100585
5_24286474

In [27]:
df_gene_info_ensembl

,block,gene_id,gene_name,start,end,biotype,description
0,1_1318,AT1G26680,AT1G26680,9219460,9223795,protein_coding,transcriptional factor B3 family protein [Sour...
1,1_1594,AT1G30710,AT1G30710,10895252,10897127,protein_coding,FAD-binding Berberine family protein [Source:N...
2,1_1594,AT1G30720,AT1G30720,10897925,10899975,protein_coding,FAD-binding Berberine family protein [Source:N...
3,1_2867,AT1G55660,AT1G55660,20800694,20802377,protein_coding,"FBD, F-box and Leucine Rich Repeat domains con..."
4,1_2867,AT1G55675,AT1G55675,20803661,20804574,protein_coding,transmembrane protein [Source:NCBI gene (forme...
...,...,...,...,...,...,...,...
116,5_2922,AT5G60335,AT5G60335,24272995,24274860,protein_coding,hydroxyacyl-thioester dehydratase type-like pr...
117,5_2922,AT5G60350,AT5G60350,24277730,24279147,protein_coding,None
118,5_2922,AT5G60370,AT5G60370,24282666,24285061,protein_coding,exonuclease V-like protein [Source:NCBI gene (...
119,5_2922,AT5G60380,AT5G60380,24285920,24287808,protein_coding,"transmembrane protein, putative (DUF239) [Sour..."
120,5_780,AT5G26805,AT5G26805,9427543,9428067,protein_coding,B3 domain protein [Source:NCBI gene (formerly ...

In [28]:
df_gene_info_ncbi

,block,gene_id,gene_name,description
0,1_2867,AT1G55670,PSAG,"Encodes subunit G of photosystem I, an 11-kDa ..."
1,1_485,AT1G11840,GLX1,Encodes a glyoxalase I homolog ATGLX1.
2,1_485,AT1G70580,AOAT2,Encodes a protein with glyoxylate aminotransfe...
3,1_485,AT1G70610,ABCB26,member of TAP subfamily
4,1_485,AT1G70660,MMZ2,MMZ2/UEV1B encodes a protein that may play a r...
...,...,...,...,...
59,5_2922,AT5G60220,TET4,Member of TETRASPANIN family
60,5_2922,AT5G60230,SEN2,putative subunit of tRNA splicing endonuclease
61,5_2922,AT5G60300,LecRK-I.9,Lectin Receptor Kinase involved in protein-pro...
62,5_2922,AT5G60340,AAK6,Encodes a nuclear adenylate kinase that intera...
63,5_2922,AT5G60360,ALP,Encodes a senescence-associated thiol protease.

In [34]:
len(flattened_gene_ids)

207

In [44]:
tair['biotype'].unique()

array(['protein_coding_gene'], dtype=object)

In [42]:
tair['gene_id'].nunique()

27206

In [38]:
flattened_gene_ids

['AT1G26680',
 'AT1G30710',
 'AT1G30720',
 'AT1G55660',
 'AT1G55670',
 'AT1G55675',
 'AT1G55680',
 'AT1G55690',
 'AT1G67560',
 'AT1G67570',
 'AT1G70020',
 'AT1G11840',
 'AT1G70580',
 'AT1G70590',
 'AT1G70600',
 'AT1G70610',
 'AT1G70620',
 'AT1G70630',
 'AT1G70640',
 'AT1G70650',
 'AT1G70660',
 'AT1G17500',
 'AT1G17510',
 'AT1G17520',
 'AT1G17530',
 'AT1G17540',
 'AT1G17545',
 'AT1G17550',
 'AT1G17560',
 'AT1G17580',
 'AT1G17590',
 'AT1G17600',
 'AT1G17610',
 'AT1G17615',
 'AT1G17620',
 'AT1G17630',
 'AT1G17640',
 'AT1G17650',
 'AT1G17665',
 'AT1G17680',
 'AT1G17690',
 'AT1G17700',
 'AT1G17710',
 'AT1G17720',
 'AT1G17730',
 'AT1G17744',
 'AT1G17745',
 'AT1G17750',
 'AT1G17760',
 'AT1G17770',
 'AT1G17780',
 'AT1G17790',
 'AT1G17800',
 'AT1G17810',
 'AT1G17820',
 'AT1G17830',
 'AT1G17840',
 'AT1G17850',
 'AT1G17860',
 'AT1G17870',
 'AT1G17880',
 'AT1G17890',
 'AT1G17910',
 'AT1G17920',
 'AT1G17930',
 'AT1G17940',
 'AT1G17950',
 'AT1G17960',
 'AT2G24230',
 'AT2G27030',
 'AT2G17380',
 'AT2G17390',
 'AT2G17410',
 'AT2G17420',
 'AT2G22475',
 'AT2G22480',
 'AT2G22490',
 'AT2G22500',
 'AT2G22510',
 'AT2G22520',
 'AT2G22530',
 'AT2G22540',
 'AT2G22560',
 'AT2G22570',
 'AT2G22590',
 'AT2G22600',
 'AT2G22610',
 'AT2G22620',
 'AT2G22630',
 'AT2G22640',
 'AT2G22650',
 'AT2G22660',
 'AT2G22670',
 'AT2G22680',
 'AT2G22690',
 'AT2G22720',
 'AT2G22730',
 'AT2G22740',
 'AT2G22750',
 'AT2G22760',
 'AT2G22770',
 'AT2G22780',
 'AT2G22790',
 'AT2G22795',
 'AT2G22800',
 'AT2G22802',
 'AT2G22805',
 'AT3G05327',
 'AT3G28580',
 'AT3G28590',
 'AT3G28600',
 'AT3G28610',
 'AT3G28620',
 'AT3G28630',
 'AT3G28640',
 'AT3G05380',
 'AT3G05390',
 'AT3G28910',
 'AT3G28917',
 'AT3G28918',
 'AT3G28920',
 'AT3G28925',
 'AT3G28930',
 'AT3G28940',
 'AT3G28950',
 'AT3G28956',
 'AT3G07350',
 'AT3G47390',
 'AT3G47400',
 'AT3G47410',
 'AT3G47420',
 'AT3G50750',
 'AT3G62360',
 'AT3G62370',
 'AT4G12110',
 'AT4G12120',
 'AT4G12130',
 'AT4G12140',
 'AT4G12150',
 'AT5G44080',
 'AT5G44090',
 'AT5G44100',
 'AT5G44110',
 'AT5G44120',
 'AT5G48560',
 'AT5G59820',
 'AT5G59830',
 'AT5G59840',
 'AT5G59845',
 'AT5G59850',
 'AT5G59860',
 'AT5G59870',
 'AT5G59880',
 'AT5G59890',
 'AT5G59900',
 'AT5G59910',
 'AT5G59920',
 'AT5G59930',
 'AT5G59940',
 'AT5G59950',
 'AT5G59960',
 'AT5G59970',
 'AT5G59980',
 'AT5G59990',
 'AT5G60000',
 'AT5G60010',
 'AT5G60020',
 'AT5G60030',
 'AT5G60040',
 'AT5G60050',
 'AT5G60060',
 'AT5G60070',
 'AT5G60080',
 'AT5G60090',
 'AT5G60100',
 'AT5G60110',
 'AT5G60120',
 'AT5G60130',
 'AT5G60140',
 'AT5G60142',
 'AT5G60150',
 'AT5G60160',
 'AT5G60170',
 'AT5G60180',
 'AT5G60190',
 'AT5G60200',
 'AT5G60210',
 'AT5G60220',
 'AT5G60230',
 'AT5G60240',
 'AT5G60250',
 'AT5G60260',
 'AT5G60270',
 'AT5G60280',
 'AT5G60290',
 'AT5G60300',
 'AT5G60310',
 'AT5G60320',
 'AT5G60330',
 'AT5G60335',
 'AT5G60340',
 'AT5G60350',
 'AT5G60360',
 'AT5G60370',
 'AT5G60380',
 'AT5G26800',
 'AT5G26805']

In [35]:
set(df_gene_info_ncbi['gene_id']).intersection(df_gene_info_ensembl['gene_id'])

set()

In [36]:
len(set(flattened_gene_ids).intersection(set(df_gene_info_ncbi['gene_id'])))

64

In [37]:
len(set(flattened_gene_ids).intersection(set(df_gene_info_ensembl['gene_id'])))

121

In [50]:
121 + 64

185

In [49]:
len(flattened_gene_ids)

207

In [28]:
df_gene_info_ensembl.merge(df_gene_info_ncbi, on = 'gene_id')

Empty DataFrame
Columns: [block_x, gene_id, gene_name_x, start, end, biotype, description_x, block_y, gene_name_y, description_y]
Index: []

In [ ]:
df_gene_info_ensembl

In [ ]:
from Bio import Entrez

# Provide your email, NCBI requires this for queries
Entrez.email = "tbellg@berkeley.edu"

# Function to retrieve gene information using NCBI Entrez API
def get_gene_info_ncbi(gene_id):
    try:
        # Search for the gene in the NCBI database
        search_handle = Entrez.esearch(db="gene", term=f"{gene_id}[Gene]", retmax=1)
        search_results = Entrez.read(search_handle)
        search_handle.close()
        
        if search_results["IdList"]:
            gene_ncbi_id = search_results["IdList"][0]  # Get the first matching gene ID
            
            # Fetch detailed gene information using the gene ID
            fetch_handle = Entrez.efetch(db="gene", id=gene_ncbi_id, retmode="xml")
            gene_data = Entrez.read(fetch_handle)
            fetch_handle.close()
            
            # Extract relevant information from the gene data
            gene_info = gene_data[0]
            gene_name = gene_info['Entrezgene_gene']['Gene-ref']['Gene-ref_locus']
            gene_desc = gene_info['Entrezgene_summary']
            return {
                "gene_id": gene_id,
                "gene_name": gene_name,
                "description": gene_desc
            }
        else:
            return None
    except Exception as e:
        print(f"Error fetching data for gene {gene_id}: {e}")
        return None

In [36]:
sign_wza_lfmm['matching_gene_id'].values

array(['AT1G26680', 'AT1G30710,AT1G30720',
       'AT1G55660,AT1G55670,AT1G55675,AT1G55680,AT1G55690',
       'AT1G67560,AT1G67570', 'AT1G70020',
       'AT1G11840,AT1G70580,AT1G70590,AT1G70600,AT1G70610,AT1G70620,AT1G70630,AT1G70640,AT1G70650,AT1G70660',
       'AT1G17500,AT1G17510,AT1G17520,AT1G17530,AT1G17540,AT1G17545,AT1G17550,AT1G17560,AT1G17580,AT1G17590,AT1G17600,AT1G17610,AT1G17615,AT1G17620,AT1G17630,AT1G17640,AT1G17650,AT1G17665,AT1G17680,AT1G17690,AT1G17700,AT1G17710,AT1G17720,AT1G17730,AT1G17744,AT1G17745,AT1G17750,AT1G17760,AT1G17770,AT1G17780,AT1G17790,AT1G17800,AT1G17810,AT1G17820,AT1G17830,AT1G17840,AT1G17850,AT1G17860,AT1G17870,AT1G17880,AT1G17890,AT1G17910,AT1G17920,AT1G17930,AT1G17940,AT1G17950,AT1G17960',
       'AT2G24230', 'AT2G27030',
       'AT2G17380,AT2G17390,AT2G17410,AT2G17420',
       'AT2G22475,AT2G22480,AT2G22490,AT2G22500,AT2G22510,AT2G22520,AT2G22530,AT2G22540,AT2G22560,AT2G22570,AT2G22590,AT2G22600,AT2G22610,AT2G22620,AT2G22630,AT2G22640,AT2G22650,AT2G22660,AT2G22670,AT2G22680,AT2G22690,AT2G22720,AT2G22730,AT2G22740,AT2G22750,AT2G22760,AT2G22770,AT2G22780,AT2G22790,AT2G22795,AT2G22800,AT2G22802,AT2G22805',
       None,
       'AT3G05327,AT3G28580,AT3G28590,AT3G28600,AT3G28610,AT3G28620,AT3G28630,AT3G28640',
       'AT3G05380,AT3G05390,AT3G28910,AT3G28917,AT3G28918,AT3G28920,AT3G28925,AT3G28930,AT3G28940,AT3G28950,AT3G28956',
       'AT3G07350,AT3G47390,AT3G47400,AT3G47410,AT3G47420', 'AT3G50750',
       'AT3G62360,AT3G62370',
       'AT4G12110,AT4G12120,AT4G12130,AT4G12140,AT4G12150',
       'AT5G44080,AT5G44090,AT5G44100,AT5G44110,AT5G44120', 'AT5G48560',
       'AT5G59820,AT5G59830,AT5G59840,AT5G59845,AT5G59850,AT5G59860,AT5G59870,AT5G59880,AT5G59890,AT5G59900,AT5G59910,AT5G59920,AT5G59930,AT5G59940,AT5G59950,AT5G59960,AT5G59970,AT5G59980,AT5G59990,AT5G60000,AT5G60010,AT5G60020,AT5G60030,AT5G60040,AT5G60050,AT5G60060,AT5G60070,AT5G60080,AT5G60090,AT5G60100,AT5G60110,AT5G60120,AT5G60130,AT5G60140,AT5G60142,AT5G60150,AT5G60160,AT5G60170,AT5G60180,AT5G60190,AT5G60200,AT5G60210,AT5G60220,AT5G60230,AT5G60240,AT5G60250,AT5G60260,AT5G60270,AT5G60280,AT5G60290,AT5G60300,AT5G60310,AT5G60320,AT5G60330,AT5G60335,AT5G60340,AT5G60350,AT5G60360,AT5G60370,AT5G60380',
       'AT5G26800,AT5G26805'], dtype=object)

In [32]:
# Get the values from 'matching_gene_id' column
matching_gene_ids = sign_wza_lfmm['matching_gene_id'].values

# Filter out None or NaN values
filtered_gene_ids = [gene_id for gene_id in matching_gene_ids if gene_id]

# Flatten the gene IDs (since some are comma-separated) into a single list
flattened_gene_ids = []
for gene_ids in filtered_gene_ids:
    flattened_gene_ids.extend(gene_ids.split(','))  # Split the comma-separated strings and extend the list

# Join all the gene IDs into a single string, separated by comma

In [45]:
len(flattened_gene_ids)

207

In [42]:
all_gene_ids_joined

'AT1G26680,AT1G30710,AT1G30720,AT1G55660,AT1G55670,AT1G55675,AT1G55680,AT1G55690,AT1G67560,AT1G67570,AT1G70020,AT1G11840,AT1G70580,AT1G70590,AT1G70600,AT1G70610,AT1G70620,AT1G70630,AT1G70640,AT1G70650,AT1G70660,AT1G17500,AT1G17510,AT1G17520,AT1G17530,AT1G17540,AT1G17545,AT1G17550,AT1G17560,AT1G17580,AT1G17590,AT1G17600,AT1G17610,AT1G17615,AT1G17620,AT1G17630,AT1G17640,AT1G17650,AT1G17665,AT1G17680,AT1G17690,AT1G17700,AT1G17710,AT1G17720,AT1G17730,AT1G17744,AT1G17745,AT1G17750,AT1G17760,AT1G17770,AT1G17780,AT1G17790,AT1G17800,AT1G17810,AT1G17820,AT1G17830,AT1G17840,AT1G17850,AT1G17860,AT1G17870,AT1G17880,AT1G17890,AT1G17910,AT1G17920,AT1G17930,AT1G17940,AT1G17950,AT1G17960,AT2G24230,AT2G27030,AT2G17380,AT2G17390,AT2G17410,AT2G17420,AT2G22475,AT2G22480,AT2G22490,AT2G22500,AT2G22510,AT2G22520,AT2G22530,AT2G22540,AT2G22560,AT2G22570,AT2G22590,AT2G22600,AT2G22610,AT2G22620,AT2G22630,AT2G22640,AT2G22650,AT2G22660,AT2G22670,AT2G22680,AT2G22690,AT2G22720,AT2G22730,AT2G22740,AT2G22750,AT2G22760,AT2G22770,AT2G22780,AT2G22790,AT2G22795,AT2G22800,AT2G22802,AT2G22805,AT3G05327,AT3G28580,AT3G28590,AT3G28600,AT3G28610,AT3G28620,AT3G28630,AT3G28640,AT3G05380,AT3G05390,AT3G28910,AT3G28917,AT3G28918,AT3G28920,AT3G28925,AT3G28930,AT3G28940,AT3G28950,AT3G28956,AT3G07350,AT3G47390,AT3G47400,AT3G47410,AT3G47420,AT3G50750,AT3G62360,AT3G62370,AT4G12110,AT4G12120,AT4G12130,AT4G12140,AT4G12150,AT5G44080,AT5G44090,AT5G44100,AT5G44110,AT5G44120,AT5G48560,AT5G59820,AT5G59830,AT5G59840,AT5G59845,AT5G59850,AT5G59860,AT5G59870,AT5G59880,AT5G59890,AT5G59900,AT5G59910,AT5G59920,AT5G59930,AT5G59940,AT5G59950,AT5G59960,AT5G59970,AT5G59980,AT5G59990,AT5G60000,AT5G60010,AT5G60020,AT5G60030,AT5G60040,AT5G60050,AT5G60060,AT5G60070,AT5G60080,AT5G60090,AT5G60100,AT5G60110,AT5G60120,AT5G60130,AT5G60140,AT5G60142,AT5G60150,AT5G60160,AT5G60170,AT5G60180,AT5G60190,AT5G60200,AT5G60210,AT5G60220,AT5G60230,AT5G60240,AT5G60250,AT5G60260,AT5G60270,AT5G60280,AT5G60290,AT5G60300,AT5G60310,AT5G60320,AT5G60330,AT5G60335,AT5G60340,AT5G60350,AT5G60360,AT5G60370,AT5G60380,AT5G26800,AT5G26805'

In [ ]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Function to retrieve gene information from NCBI using the API
def get_gene_info_ncbi(gene_id):
    url = f"https://api.ncbi.nlm.nih.gov/datasets/v2alpha/gene/id/{gene_id}/download_summary"
    headers = {"accept": "application/json"}
    
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        # Return the JSON response
        return response.json()
    else:
        return None  # Return None if the request failed

# Example gene IDs (from your dataset)
gene_ids = ['59067', '7157']  # Replace these with the actual gene IDs from your dataset

# Fetch information for each gene
gene_info_list = []

for gene_id in gene_ids:
    gene_info = get_gene_info_ncbi(gene_id)
    if gene_info:
        # Extract relevant data from the response
        gene_data = {
            "gene_id": gene_id,
            "gene_name": gene_info['gene']['name'],
            "description": gene_info['gene']['description']
        }
        gene_info_list.append(gene_data)

# Convert the list of gene information to a DataFrame for easier handling
df_gene_info = pd.DataFrame(gene_info_list)

# Display the gene information DataFrame
print(df_gene_info)

# Now, assuming we have significant blocks from your data
# Let's integrate the gene information with the plot

# Significance threshold
threshold_value = 0.05 / len(wza_lfmm)
threshold = -np.log10(threshold_value)
biovar = 'bio1'

# Create chrom_pos in wza_lfmm by combining 'chrom' and 'pos'
wza_lfmm['chrom_pos'] = wza_lfmm['chrom'].astype(str) + '_' + wza_lfmm['pos'].astype(str)

# Copy the relevant columns for plotting
df = wza_lfmm[['Z_pVal', 'pos', 'chrom', 'chrom_pos']].copy()

# Parse chromosome number and position
df['chromosome'] = df['chrom']
df['position'] = df['pos']
df['-log10(pvalue)'] = -np.log10(df['Z_pVal'])

# Define colors for each chromosome or block
colors = sns.color_palette("crest", n_colors=len(df['chromosome'].unique()))  # Assign a unique color per chromosome

# Calculate chromosome offsets to prevent overlap
chromosome_offsets = {}
offset = 0
for chrom in sorted(df['chromosome'].unique()):
    chromosome_offsets[chrom] = offset
    max_position = df[df['chromosome'] == chrom]['position'].max()
    offset += max_position + 200  # Add buffer to prevent overlap

# Apply offsets to the position
df['adjusted_position'] = df.apply(lambda row: row['position'] + chromosome_offsets[row['chromosome']], axis=1)

# Create the Manhattan plot
plt.figure(figsize=(20, 6))

# Plot each chromosome separately
for chrom in sorted(df['chromosome'].unique()):
    subset = df[df['chromosome'] == chrom]
    plt.scatter(
        subset['adjusted_position'],
        subset

In [ ]:
1_1594

In [8]:
## all samples wza on kendalltau
wza_kendall = pd.read_csv('../wza/wza_kendalltau_results_bio1.csv')

In [9]:
sign_wza_kendall = wza_kendall[wza_kendall['Z_pVal'] <= 0.05/len(wza_kendall)]

In [10]:
sign_wza_kendall.sort_values('Z_pVal')

         gene  SNPs  hits          Z  top_candidate_p        Z_pVal
5406   2_1264  1885     0   2.057459     1.000000e+00  0.000000e+00
7217    2_973  1843     5  10.919003     9.999435e-01  0.000000e+00
10099   3_551  1849     4   5.318958     9.999891e-01  0.000000e+00
12569  4_2808  1729   220  20.956158    1.191537e-162  1.110223e-16
13384   4_801   225   146  31.615317    5.445274e-231  2.907737e-10
9133   3_2730    53    30  15.113784     4.984762e-46  2.548200e-09
7135    2_897    30    18  11.773300     7.715812e-29  4.589528e-08
431    1_1391    27    19  11.351576     2.056867e-32  6.736171e-08
3851   1_4506   109     8  17.976827     1.550062e-05  1.090242e-07
6199    2_199    10     9   9.224959     9.910000e-18  3.637041e-07
5407   2_1265    16     5   9.028052     3.984317e-07  2.119224e-06
48     1_1040    93    37  14.712225     6.834746e-49  2.455139e-06

In [ ]:
kendall_sign = ['2_1264', '2_973' '3_551', '4_2808']

In [11]:
pd.merge(sign_wza_kendall,sign_wza_lfmm, on = 'gene')

,gene,SNPs_x,hits_x,Z_x,top_candidate_p_x,Z_pVal_x,SNPs_y,hits_y,Z_y,top_candidate_p_y,Z_pVal_y
0,2_1265,16,5,9.028052,3.984317e-07,2.119224e-06,16,15,11.151806,1.585000e-29,1.569795e-08
1,4_801,225,146,31.615317,5.445274e-231,2.907737e-10,225,130,23.960528,7.309601e-196,1.040595e-06

In [12]:
genes = ['2_1265', '4_801']

In [11]:
linages_wza_picmin = pd.read_csv('../linages_wza_picmin/linage_based_kendall_wza_picmin.csv')

In [21]:
linages_wza_picmin[linages_wza_picmin['n_est'] ==12].sort_values('p')

,index,numLin,p,q,n_est,locus,redundan,scaffold,start,chrom,pos
4172,4172,12,0.000024,0.001955,12,1_4847,1,4847,NaN,1,4847
12438,12438,12,0.000036,0.002633,12,4_2817,4,2817,NaN,4,2817
13736,13736,12,0.000337,0.015449,12,5_1272,5,1272,NaN,5,1272
5818,5818,12,0.000523,0.022242,12,2_170,2,170,NaN,2,170
259,259,12,0.000574,0.023699,12,1_1239,1,1239,NaN,1,1239
...,...,...,...,...,...,...,...,...,...,...,...
14707,14707,12,1.000000,1.000000,12,5_2166,5,2166,NaN,5,2166
12717,12717,12,1.000000,1.000000,12,4_325,4,325,NaN,4,325
9730,9730,12,1.000000,1.000000,12,3_3372,3,3372,NaN,3,3372
8996,8996,12,1.000000,1.000000,12,3_2698,3,2698,NaN,3,2698
12714,12714,12,1.000000,1.000000,12,4_322,4,322,NaN,4,322

In [12]:
th = 0.05/len(linages_wza_picmin)

In [13]:
sign_linages_wza_picmin = linages_wza_picmin[linages_wza_picmin['p'] <= th]

In [14]:
sign_linages_wza_picmin = sign_linages_wza_picmin.rename(columns = {'locus':'gene'})

In [17]:
sign_linages_wza_picmin.sort_values('n_est')

,index,numLin,p,q,n_est,gene,redundan,scaffold,start,chrom,pos
48,48,12,9.999990e-07,0.000158,2,1_1040,1,1040,NaN,1,1040
9684,9684,12,9.999990e-07,0.000158,2,3_3330,3,3330,NaN,3,3330
9683,9683,12,9.999990e-07,0.000158,2,3_333,3,333,NaN,3,333
9440,9440,12,9.999990e-07,0.000158,2,3_3104,3,3104,NaN,3,3104
9033,9033,12,9.999990e-07,0.000158,2,3_2730,3,2730,NaN,3,2730
...,...,...,...,...,...,...,...,...,...,...,...
14579,14579,12,9.999990e-07,0.000158,7,5_2048,5,2048,NaN,5,2048
3058,3058,12,9.999990e-07,0.000158,7,1_3821,1,3821,NaN,1,3821
3863,3863,12,9.999990e-07,0.000158,8,1_4562,1,4562,NaN,1,4562
15070,15070,12,9.999990e-07,0.000158,8,5_2505,5,2505,NaN,5,2505
11347,11347,12,2.999997e-06,0.000380,8,4_1803,4,1803,NaN,4,1803

In [ ]:
## 8 lineages adn significant 
lineages = ['4_1803', '5_2505', '1_4562' ]

# 12 lineages most significant 
lineages = ['1_4847']

In [15]:
sign_linages_wza_picmin.merge(sign_wza_kendall, on = 'gene')

,index,numLin,p,q,n_est,gene,redundan,scaffold,start,chrom,pos,SNPs,hits,Z,top_candidate_p,Z_pVal
0,48,12,9.999990e-07,0.000158,2,1_1040,1,1040,NaN,1,1040,93,37,14.712225,6.834746e-49,2.455139e-06
1,425,12,9.999990e-07,0.000158,3,1_1391,1,1391,NaN,1,1391,27,19,11.351576,2.056867e-32,6.736171e-08
2,3802,12,9.999990e-07,0.000158,2,1_4506,1,4506,NaN,1,4506,109,8,17.976827,1.550062e-05,1.090242e-07
3,5348,12,9.999990e-07,0.000158,5,2_1265,2,1265,NaN,2,1265,16,5,9.028052,3.984317e-07,2.119224e-06
4,6132,12,9.999990e-07,0.000158,6,2_199,2,199,NaN,2,199,10,9,9.224959,9.910000e-18,3.637041e-07
5,7058,12,9.999990e-07,0.000158,6,2_897,2,897,NaN,2,897,30,18,11.773300,7.715812e-29,4.589528e-08
6,9033,12,9.999990e-07,0.000158,2,3_2730,3,2730,NaN,3,2730,53,30,15.113784,4.984762e-46,2.548200e-09
7,9989,12,9.999990e-07,0.000158,2,3_551,3,551,NaN,3,551,1849,4,5.318958,9.999891e-01,0.000000e+00
8,12428,12,9.999990e-07,0.000158,2,4_2808,4,2808,NaN,4,2808,1729,220,20.956158,1.191537e-162,1.110223e-16
9,13229,12,9.999990e-07,0.000158,4,4_801,4,801,NaN,4,801,225,146,31.615317,5.445274e-231,2.907737e-10

In [23]:
genes = ['2_1265', '4_801']

In [28]:
sign_wza_lfmm.merge(sign_linages_wza_picmin, on = 'gene').merge(sign_wza_kendall, on = 'gene')

,gene,SNPs_x,hits_x,Z_x,top_candidate_p_x,Z_pVal_x,index,numLin,p,q,...,redundan,scaffold,start,chrom,pos,SNPs_y,hits_y,Z_y,top_candidate_p_y,Z_pVal_y
0,2_1265,16,15,11.151806,1.585000e-29,1.569795e-08,5348,12,9.999990e-07,0.000158,...,2,1265,NaN,2,1265,16,5,9.028052,3.984317e-07,2.119224e-06
1,4_801,225,130,23.960528,7.309601e-196,1.040595e-06,13229,12,9.999990e-07,0.000158,...,4,801,NaN,4,801,225,146,31.615317,5.445274e-231,2.907737e-10

In [30]:
gemma = pd.read_csv('/carnegie/nobackup/scratch/tbellagio/gea_grene-net/gwas/allele_assoc_runs/lmm_gemma/bio1/output/results_lmm.csv')

In [37]:
gemma_sign_blocks = gemma.groupby('blocks')['significant'].sum()[gemma.groupby('blocks')['significant'].sum() !=0].reset_index()

In [39]:
gemma_sign_blocks.merge(sign_wza_lfmm, left_on = 'blocks', right_on = 'gene')

Empty DataFrame
Columns: [blocks, significant, gene, SNPs, hits, Z, top_candidate_p, Z_pVal]
Index: []

In [40]:
gemma_sign_blocks.merge(sign_linages_wza_picmin, left_on = 'blocks', right_on = 'gene')

Empty DataFrame
Columns: [blocks, significant, index, numLin, p, q, n_est, gene, redundan, scaffold, start, chrom, pos]
Index: []

In [41]:
gemma_sign_blocks.merge(sign_wza_kendall, left_on = 'blocks', right_on = 'gene')

  blocks  significant   gene  SNPs  hits          Z  top_candidate_p  Z_pVal
0  2_973            4  2_973  1843     5  10.919003         0.999944     0.0

In [ ]:
#### addd to the annotated genes the blocks

In [34]:
import pickle
dict_blocks = '../key_files/blocks_snpsid_dict.pkl'

with open(dict_blocks, 'rb') as file:
    dict_blocks = pickle.load(file)

reverse_mapping = {item: key for key, values in dict_blocks.items() for item in values}

In [35]:
gff3_formatted = pd.read_csv('../key_files/TAIR10_GFF3_genes_transposons_formatted4topr.csv')

In [37]:
from collections import defaultdict

In [60]:
# create clock ranges
blocks_ranges = {}
for key, values in dict_blocks.items():
    chromosome = dict_blocks[key][0].split('_')[0]
    start = dict_blocks[key][0].split('_')[1]
    end = dict_blocks[key][-1].split('_')[1]
    blocks_ranges[key] = [int(chromosome), int(start), int(end)]

In [70]:
# Step 2: Function to check if a gene falls within one or more blocks
def find_gene_blocks(chrom, gene_start, gene_end):
    matching_blocks = []
    for block, values in blocks_ranges.items():
        block_chrom, block_start, block_end = values
        if chrom == block_chrom:
            # Check if the gene overlaps with the block
            if (block_start <= gene_start <= block_end) or (block_start <= gene_end <= block_end) or (gene_start <= block_start <= gene_end):
                matching_blocks.append(block)
    return matching_blocks if matching_blocks else 'No matching block'

# Step 3: Apply the function to the dataframe

gff3_formatted['blocks'] = gff3_formatted.apply(lambda row: find_gene_blocks(row['chrom'], row['gene_start'], row['gene_end']), axis=1)

In [72]:
gff3_formatted.to_csv('../key_files/TAIR10_GFF3_genes_transposons_formatted4topr_w_blocks',index=None)

In [73]:
gff3_formatted

,Unnamed: 0,chrom,gene_start,gene_end,gene_symbol,biotype,gene_id,exon_chromstart,exon_chromend,blocks
0,0,1,3631,5899,AT1G01010,protein_coding_gene,AT1G01010,"3631,3996,4486,4706,5174,5439","3913,4276,4605,5095,5326,5899",[1_0]
1,6,1,5928,8737,AT1G01020,protein_coding_gene,AT1G01020,"8571,8417,8236,7942,7762,7564,7384,7157,6437,5...","8737,8464,8325,7987,7835,7649,7450,7232,7069,6...",[1_0]
2,24,1,11649,13714,AT1G01030,protein_coding_gene,AT1G01030,"13335,11649","13714,13173",[1_0]
3,26,1,23146,31227,AT1G01040,protein_coding_gene,AT1G01040,"23146,24542,24752,25041,25524,25825,26081,2629...","24451,24655,24962,25435,25743,25997,26203,2645...",[1_0]
4,66,1,31170,33153,AT1G01050,protein_coding_gene,AT1G01050,"33029,32547,32431,32282,32088,31933,31693,3152...","33153,32670,32459,32347,32195,31998,31813,3160...",[1_0]
...,...,...,...,...,...,...,...,...,...,...
27201,207189,5,26959569,26960323,AT5G67600,protein_coding_gene,AT5G67600,"26960181,26959937,26959569","26960323,26960093,26959799",[5_3109]
27202,207192,5,26960931,26963638,AT5G67610,protein_coding_gene,AT5G67610,"26963509,26963122,26962863,26962648,26962503,2...","26963638,26963335,26963020,26962793,26962562,2...",[5_3109]
27203,207212,5,26964770,26965996,AT5G67620,protein_coding_gene,AT5G67620,"26965468,26965198,26964770","26965996,26965379,26965004",[5_3109]
27204,207215,5,26967381,26969394,AT5G67630,protein_coding_gene,AT5G67630,"26968558,26967381","26969394,26968195",[5_3109]
27205,207217,5,26969546,26970641,AT5G67640,protein_coding_gene,AT5G67640,"26970444,26970312,26969915,26969546","26970641,26970360,26970241,26969670",[5_3109]